version: '3.7'
services:
  whoami1:
    image: "containous/whoami"
    networks:
      - traefik-net
    labels:
      - "subdomain=whoami1"
      - "traefik.enable=true"
      - "traefik.http.routers.whoami1.entrypoints=https"
      - "traefik.http.routers.whoami1.tls.certresolver=letsencrypt"
      # redirect
      - "traefik.http.routers.whoami1-redirect.entrypoints=http"
      - "traefik.http.routers.whoami1-redirect.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
  whoami2:
    image: "containous/whoami"
    networks:
      - traefik-net
    labels:
      - "subdomain=whoami2"
      - "traefik.enable=true"
      - "traefik.http.routers.whoami2.entrypoints=https"
      - "traefik.http.routers.whoami2.tls.certresolver=letsencrypt"
      # redirect
      - "traefik.http.routers.whoami2-redirect.entrypoints=http"
      - "traefik.http.routers.whoami2-redirect.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
networks:
  traefik-net:
    external: true
