version: '3.7'
services:
  kuard:
    image: gcr.io/kuar-demo/kuard-amd64:1
    networks:
      - traefik-net
    ports:
      - 8080
    labels:
      - "subdomain=kuard"
      - "traefik.enable=true"
      - "traefik.http.routers.kuard.entrypoints=https"
      - "traefik.http.routers.kuard.tls.certresolver=letsencrypt"
      # redirect
      - "traefik.http.routers.kuard-redirect.entrypoints=http"
      - "traefik.http.routers.kuard-redirect.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
networks:
  traefik-net:
    external: true
